import { ThreadEvent, ThreadEventSchema } from '@/app/schemas/realtime';
import { orpc } from '@/lib/orpc';
import { useQueryClient } from '@tanstack/react-query';
import usePartySocket from 'partysocket/react';
import { createContext, ReactNode, useContext, useMemo } from 'react';

type Props = {
  threadId: string;
  children: ReactNode;
};

type ThreadRealtimeContextValue = {
  send: (event: ThreadEvent) => void;
};
const ThreadRealtimeContext = createContext<ThreadRealtimeContextValue | null>(
  null,
);

export const ThreadRealtimeProvider = ({ threadId, children }: Props) => {
  const queryClient = useQueryClient();

  type ThreadListOptions = ReturnType<
    typeof orpc.message.thread.list.queryOptions
  >;
  type ThreadQueryData = Awaited<ReturnType<ThreadListOptions['queryFn']>>;

  const socket = usePartySocket({
    host: 'https://teamflow-realtime.fenintolja.workers.dev',
    room: `thread-${threadId}`,
    party: 'chat',
    onMessage(e) {
      try {
        const parsed = JSON.parse(e.data);

        const result = ThreadEventSchema.safeParse(parsed);

        if (!result.success) {
          console.warn('Invalid thread event', result.error);
          return;
        }

        const event = result.data;

        if (event.type === 'thread:reply:created') {
          const replyObject = event.payload.reply;

          //use the same key generated by orpc
          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId },
          });

          queryClient.setQueryData<ThreadQueryData>(
            listOptions.queryKey,
            (old) => {
              if (!old) return old;

              const reply = {
                ...replyObject,
                reactions: Array.isArray(replyObject.reactions)
                  ? replyObject.reactions
                  : [],
              } as ThreadQueryData['messages'][number];

              return { ...old, messages: [...old.messages, reply] };
            },
          );

          return;
        }

        if (event.type === 'thread:reaction:updated') {
          const { messageId, reactions, threadId: tId } = event.payload;

          if (threadId !== tId) return;

          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId },
          });

          queryClient.setQueryData<ThreadQueryData>(
            listOptions.queryKey,
            (old) => {
              if (!old) return old;

              if (messageId === threadId) {
                return {
                  ...old,
                  parent: { ...old.parent, reactions },
                };
              }

              return {
                ...old,
                messages: old.messages.map((m) =>
                  m.id === messageId ? { ...m, reactions } : m,
                ),
              };
            },
          );

          return;
        }
      } catch {
        console.log('Something went wrong');
      }
    },
  });
  const value = useMemo<ThreadRealtimeContextValue>(() => {
    return {
      send: (event) => {
        socket.send(JSON.stringify(event));
      },
    };
  }, [socket]);

  return (
    <ThreadRealtimeContext.Provider value={value}>
      {children}
    </ThreadRealtimeContext.Provider>
  );
};

export function useThreadRealTime() {
  const ctx = useContext(ThreadRealtimeContext);

  if (!ctx) {
    throw new Error(
      'useThreadRealTime must be used within ThreadRealtimeProvider',
    );
  }
  return ctx;
}

export function useOptionalThreadRealTime(): ThreadRealtimeContextValue | null {
  return useContext(ThreadRealtimeContext);
}
